baseURL = 'https://leomurca.xyz'
title = 'Leonardo Murça'
defaultContentLanguage='en'

enableRobotsTXT = true

# Code Highlight
pygmentsstyle = "gruvbox"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# RSS Feed
rssLimit = 20
copyright = "copyright"

[params]
  description = "home-page-description"
  featured_image = "/img/avatar.webp"

[author]
	name = "Leonardo Murça"
	email = "leo@leomurca.xyz"

[languages]
  [languages.en]
    languageCode = 'en'
    contentDir = 'content/en'

    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "Home"
        url = "/"
        weight = 1

      [[languages.en.menu.main]]
        name = "All posts"
        url = "/posts"
        weight = 2

      [[languages.en.menu.main]]
        name = "Contact me"
        url = "/contact"
        weight = 3

      [[languages.en.menu.main]]
        name = "Donate"
        url = "/donate"
        weight = 4

  [languages.pt-br]
    languageCode = 'pt-br'
    contentDir = 'content/pt-br'

    [languages.pt-br.menu]
      [[languages.pt-br.menu.main]]
        name = "Página Inicial"
        url = "/pt-br"
        weight = 1

      [[languages.pt-br.menu.main]]
        name = "Publicações"
        url = "/pt-br/posts"
        weight = 2

      [[languages.pt-br.menu.main]]
        name = "Contato"
        url = "/pt-br/contato"
        weight = 3

      [[languages.pt-br.menu.main]]
        name = "Doe"
        url = "/pt-br/doe"
        weight = 4
