baseURL = 'https://leomurca.xyz'
languageCode = 'en-us'
title = 'Leonardo Murça'

# Code Highlight
pygmentsstyle = "gruvbox"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2