baseURL = 'https://leomurca.xyz'
languageCode = 'en-us'
title = 'Leonardo Murça'

enableRobotsTXT = true

# Code Highlight
pygmentsstyle = "github"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# RSS Feed
rssLimit = 20
copyright = "2022 Leonardo Murça All rights reserved"

[params]
  description = "Leonardo Murça Webpage"
  featured_image = "/img/avatar.webp"

[author]
	name = "Leonardo Murça"
	email = "leo@leomurca.xyz"

[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "All posts"
  url = "/posts"
  weight = 2

  [[menu.main]]
  name = "Contact me"
  url = "/contact"
  weight = 3

  [[menu.main]]
  name = "Donate"
  url = "/donate"
  weight = 4
